<a href="https://colab.research.google.com/github/prachii15/Big-data-lab/blob/main/BD_T(A).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment 1

## Task A: Develop Python code to perform block multiplication on two given matrices.

In [ ]:
import numpy as np

def b_multiply(a, b, b_size):
    r_a, c_a, c_b = len(a), len(a[0]), len(b[0])
    result = np.zeros((r_a, c_b))

    for i in range(0, r_a, b_size):
        for j in range(0, c_b, b_size):
            for k in range(0, c_a, b_size):
                block_a = a[i:i+b_size, k:k+b_size]
                block_b = b[k:k+b_size, j:j+b_size]
                result[i:i+b_size, j:j+b_size] += np.dot(block_a, block_b)

    return result.tolist()

def print_matrix(matrix, label):
    print(f"\nMatrix {label}:")
    for row in matrix:
        print(row)

n = int(input("Please enter the number: "))
c = 2 * n
d = 2 * n

# Generate random matrices
a = np.random.randint(100, size=(c, d))
b = np.random.randint(100, size=(c, d))

print_matrix(a, "A")
print_matrix(b, "B")

b_size = n
result = b_multiply(a, b, b_size)

print_matrix(result, "Result")


Please enter the number: 2

Matrix A:
[85 17 36 24]
[76 52 95 80]
[11 47 13 27]
[91 49 89 17]

Matrix B:
[58 79 82 92]
[63 89 55 58]
[79 53 68 75]
[23  8 36 87]

Matrix Result:
[9397.0, 10328.0, 11217.0, 13594.0]
[17029.0, 16307.0, 18432.0, 24093.0]
[5247.0, 5957.0, 5343.0, 7062.0]
[15787.0, 16403.0, 16821.0, 19368.0]
